---
output: 
  pdf_document:
    fig_caption: yes
params: 
  year: 
---

<!-- ```{r source_figs, message = FALSE, warning = FALSE, echo = FALSE} -->
<!-- source(here::here('functions/waterfowl_survey_functions.R')) -->
<!-- ``` -->

```{r parameters, message = FALSE, warning = FALSE, echo = FALSE}
library(knitr)
opts_knit$set(eval.after = "fig.cap")
survey_year <- params$year
```

```{r transect_map, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = "\\label{fig:transect_map}Wisconsin Waterfowl Breeding Population Survey aerial transects (*n* = 66) labeled by survey region. The four regions surveyed are the Northern High Density region (NHI), Northern Low Density region (NLO), Southeast Central region (SEC), and Southwest Driftless region (SWD)."}
plot_transect_map()
```

\newpage

```{r wetland_abundance, message = FALSE, warning = FALSE, echo = FALSE, fig.cap =  paste0("\\label{fig:wetland_abundance}", "Annual variability in total linear and non-linear wetlands per square mile by survey region. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_wetland_abundance()
```

\newpage

<!-- ```{r wetland_abundance_nhi, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:wetland_abundance_nhi}", "Annual variability in total non-linear and linear wetlands surveyed in the Northern High Density region, 1973--", survey_year, ".")} -->
<!-- plot_wetland_abundance(region_code = 2) -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r wetland_abundance_nlo, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:wetland_abundance_nlo}", "Annual variability in total non-linear and linear wetlands surveyed in the Northern Low Density region, 1973--", survey_year, ".")} -->
<!-- plot_wetland_abundance(region_code = 3) -->
<!-- ``` -->

<!-- \newpage -->

<!-- ```{r wetland_abundance_swd, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:wetland_abundance_swd}", "Annual variability in total non-linear and linear wetlands surveyed in the Southwest Driftless region, 1997--", survey_year, ".")} -->
<!-- plot_wetland_abundance(region_code = 4) -->
<!-- ``` -->

<!-- \newpage -->


```{r ssm_mall, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_mall}", "Annual statewide estimates of breeding mallard population size in Wisconsin, 1973--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'mallard')
```

\newpage

```{r ssm_bwte, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_bwte}", "Annual statewide estimates of breeding blue-winged teal abundance in Wisconsin, 1973--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'blue-winged teal')
```

\newpage

```{r ssm_wodu, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_wodu}", "Annual statewide estimates of breeding wood duck abundance in Wisconsin, 1973--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'wood duck')
```

\newpage

```{r ssm_other_ducks, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_other_ducks}", "Annual statewide estimates of breeding 'other duck' abundance in Wisconsin, 1973--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'other ducks')
```

\newpage

```{r ssm_total_ducks, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_total_ducks}", "Annual statewide estimates of total breeding duck abundance in Wisconsin, 1973--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'total ducks')
```

\newpage

```{r ssm_cago, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_cago}", "Annual statewide estimates of breeding Canada goose abundance in Wisconsin, 1986--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'canada goose')
```

\newpage

```{r annual_crane_counts, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:annual_crane_counts}", "Annual counts of sandhill cranes (raw estimates) observed from the air during the Waterfowl Breeding Population Survey, 1996--", survey_year, ". Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_crane_counts()
```

\newpage

```{r ssm_trsw, message = FALSE, warning = FALSE, echo = FALSE, fig.cap = paste0("\\label{fig:ssm_trsw}", "Annual statewide estimates of trumpeter swan abundance in Wisconsin, 2005--", survey_year, ". Black line and gray shaded region are the mean and 95% credible interval estimates for the state-space population trend, and blue points and dashed line show the annual survey counts. Note that surveys were not conducted in 2020 due to the COVID-19 pandemic.")}
plot_state_space_abundance(spp = 'trumpeter swan') 
```

