---
output:
  html_document:
    df_print: paged
  pdf_document:
---

```{r source, message = FALSE, warning = FALSE, echo = FALSE}
source(here::here('scripts/rmarkdown_functions.R'))
```


```{r wetland_tab_sec, message = FALSE, warning = FALSE, echo = FALSE}
create_wetland_summary_table(region_code = 1)
```

\newpage

```{r wetland_tab_nhi, message = FALSE, warning = FALSE, echo = FALSE}
create_wetland_summary_table(region_code = 2)
```

\newpage

```{r wetland_tab_nlo, message = FALSE, warning = FALSE, echo = FALSE}
create_wetland_summary_table(region_code = 3)
```

\newpage

```{r wetland_tab_swd, message = FALSE, warning = FALSE, echo = FALSE}
create_wetland_summary_table(region_code = 4)
```

\newpage

```{r current_breeding_estimate_table, message = FALSE, warning = FALSE, echo = FALSE}
options(knitr.kable.NA = '')
create_current_breeding_estimate_table()
```

\newpage

```{r annual_state_space_estimates_table, message = FALSE, warning = FALSE, echo = FALSE}
create_survey_state_space_estimates_table()
```

\newpage

```{r trump_tab, message = FALSE, warning = FALSE, echo = FALSE}
options(knitr.kable.NA = '')
create_trumpeter_table(start_year = 2010)
```

